// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package grpc

import (
	"context"
	"time"

	"github.com/eshadow1/gophkeeper/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockKeepService creates a new instance of MockKeepService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockKeepService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockKeepService {
	mock := &MockKeepService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockKeepService is an autogenerated mock type for the KeepService type
type MockKeepService struct {
	mock.Mock
}

type MockKeepService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockKeepService) EXPECT() *MockKeepService_Expecter {
	return &MockKeepService_Expecter{mock: &_m.Mock}
}

// CreateItem provides a mock function for the type MockKeepService
func (_mock *MockKeepService) CreateItem(ctx context.Context, item *model.ItemDB) (*model.ItemDB, error) {
	ret := _mock.Called(ctx, item)

	if len(ret) == 0 {
		panic("no return value specified for CreateItem")
	}

	var r0 *model.ItemDB
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.ItemDB) (*model.ItemDB, error)); ok {
		return returnFunc(ctx, item)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.ItemDB) *model.ItemDB); ok {
		r0 = returnFunc(ctx, item)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ItemDB)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.ItemDB) error); ok {
		r1 = returnFunc(ctx, item)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKeepService_CreateItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateItem'
type MockKeepService_CreateItem_Call struct {
	*mock.Call
}

// CreateItem is a helper method to define mock.On call
//   - ctx context.Context
//   - item *model.ItemDB
func (_e *MockKeepService_Expecter) CreateItem(ctx interface{}, item interface{}) *MockKeepService_CreateItem_Call {
	return &MockKeepService_CreateItem_Call{Call: _e.mock.On("CreateItem", ctx, item)}
}

func (_c *MockKeepService_CreateItem_Call) Run(run func(ctx context.Context, item *model.ItemDB)) *MockKeepService_CreateItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.ItemDB
		if args[1] != nil {
			arg1 = args[1].(*model.ItemDB)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockKeepService_CreateItem_Call) Return(itemDB *model.ItemDB, err error) *MockKeepService_CreateItem_Call {
	_c.Call.Return(itemDB, err)
	return _c
}

func (_c *MockKeepService_CreateItem_Call) RunAndReturn(run func(ctx context.Context, item *model.ItemDB) (*model.ItemDB, error)) *MockKeepService_CreateItem_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteItem provides a mock function for the type MockKeepService
func (_mock *MockKeepService) DeleteItem(ctx context.Context, item *model.ItemDB) error {
	ret := _mock.Called(ctx, item)

	if len(ret) == 0 {
		panic("no return value specified for DeleteItem")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.ItemDB) error); ok {
		r0 = returnFunc(ctx, item)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockKeepService_DeleteItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteItem'
type MockKeepService_DeleteItem_Call struct {
	*mock.Call
}

// DeleteItem is a helper method to define mock.On call
//   - ctx context.Context
//   - item *model.ItemDB
func (_e *MockKeepService_Expecter) DeleteItem(ctx interface{}, item interface{}) *MockKeepService_DeleteItem_Call {
	return &MockKeepService_DeleteItem_Call{Call: _e.mock.On("DeleteItem", ctx, item)}
}

func (_c *MockKeepService_DeleteItem_Call) Run(run func(ctx context.Context, item *model.ItemDB)) *MockKeepService_DeleteItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.ItemDB
		if args[1] != nil {
			arg1 = args[1].(*model.ItemDB)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockKeepService_DeleteItem_Call) Return(err error) *MockKeepService_DeleteItem_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockKeepService_DeleteItem_Call) RunAndReturn(run func(ctx context.Context, item *model.ItemDB) error) *MockKeepService_DeleteItem_Call {
	_c.Call.Return(run)
	return _c
}

// GetItems provides a mock function for the type MockKeepService
func (_mock *MockKeepService) GetItems(ctx context.Context, userID string, timeUpdate time.Time) ([]*model.ItemDB, error) {
	ret := _mock.Called(ctx, userID, timeUpdate)

	if len(ret) == 0 {
		panic("no return value specified for GetItems")
	}

	var r0 []*model.ItemDB
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time) ([]*model.ItemDB, error)); ok {
		return returnFunc(ctx, userID, timeUpdate)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time) []*model.ItemDB); ok {
		r0 = returnFunc(ctx, userID, timeUpdate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.ItemDB)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, time.Time) error); ok {
		r1 = returnFunc(ctx, userID, timeUpdate)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKeepService_GetItems_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetItems'
type MockKeepService_GetItems_Call struct {
	*mock.Call
}

// GetItems is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - timeUpdate time.Time
func (_e *MockKeepService_Expecter) GetItems(ctx interface{}, userID interface{}, timeUpdate interface{}) *MockKeepService_GetItems_Call {
	return &MockKeepService_GetItems_Call{Call: _e.mock.On("GetItems", ctx, userID, timeUpdate)}
}

func (_c *MockKeepService_GetItems_Call) Run(run func(ctx context.Context, userID string, timeUpdate time.Time)) *MockKeepService_GetItems_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockKeepService_GetItems_Call) Return(itemDBs []*model.ItemDB, err error) *MockKeepService_GetItems_Call {
	_c.Call.Return(itemDBs, err)
	return _c
}

func (_c *MockKeepService_GetItems_Call) RunAndReturn(run func(ctx context.Context, userID string, timeUpdate time.Time) ([]*model.ItemDB, error)) *MockKeepService_GetItems_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateItem provides a mock function for the type MockKeepService
func (_mock *MockKeepService) UpdateItem(ctx context.Context, item *model.ItemDB) error {
	ret := _mock.Called(ctx, item)

	if len(ret) == 0 {
		panic("no return value specified for UpdateItem")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.ItemDB) error); ok {
		r0 = returnFunc(ctx, item)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockKeepService_UpdateItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateItem'
type MockKeepService_UpdateItem_Call struct {
	*mock.Call
}

// UpdateItem is a helper method to define mock.On call
//   - ctx context.Context
//   - item *model.ItemDB
func (_e *MockKeepService_Expecter) UpdateItem(ctx interface{}, item interface{}) *MockKeepService_UpdateItem_Call {
	return &MockKeepService_UpdateItem_Call{Call: _e.mock.On("UpdateItem", ctx, item)}
}

func (_c *MockKeepService_UpdateItem_Call) Run(run func(ctx context.Context, item *model.ItemDB)) *MockKeepService_UpdateItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.ItemDB
		if args[1] != nil {
			arg1 = args[1].(*model.ItemDB)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockKeepService_UpdateItem_Call) Return(err error) *MockKeepService_UpdateItem_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockKeepService_UpdateItem_Call) RunAndReturn(run func(ctx context.Context, item *model.ItemDB) error) *MockKeepService_UpdateItem_Call {
	_c.Call.Return(run)
	return _c
}
