// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package grpc

import (
	"context"

	"github.com/eshadow1/gophkeeper/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAuthenticator creates a new instance of MockAuthenticator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthenticator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthenticator {
	mock := &MockAuthenticator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthenticator is an autogenerated mock type for the Authenticator type
type MockAuthenticator struct {
	mock.Mock
}

type MockAuthenticator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthenticator) EXPECT() *MockAuthenticator_Expecter {
	return &MockAuthenticator_Expecter{mock: &_m.Mock}
}

// Login provides a mock function for the type MockAuthenticator
func (_mock *MockAuthenticator) Login(ctx context.Context, user *model.UserUnsave) (string, error) {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.UserUnsave) (string, error)); ok {
		return returnFunc(ctx, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.UserUnsave) string); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.UserUnsave) error); ok {
		r1 = returnFunc(ctx, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthenticator_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockAuthenticator_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - user *model.UserUnsave
func (_e *MockAuthenticator_Expecter) Login(ctx interface{}, user interface{}) *MockAuthenticator_Login_Call {
	return &MockAuthenticator_Login_Call{Call: _e.mock.On("Login", ctx, user)}
}

func (_c *MockAuthenticator_Login_Call) Run(run func(ctx context.Context, user *model.UserUnsave)) *MockAuthenticator_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.UserUnsave
		if args[1] != nil {
			arg1 = args[1].(*model.UserUnsave)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthenticator_Login_Call) Return(s string, err error) *MockAuthenticator_Login_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockAuthenticator_Login_Call) RunAndReturn(run func(ctx context.Context, user *model.UserUnsave) (string, error)) *MockAuthenticator_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function for the type MockAuthenticator
func (_mock *MockAuthenticator) Register(ctx context.Context, user *model.UserUnsave) (string, error) {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.UserUnsave) (string, error)); ok {
		return returnFunc(ctx, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.UserUnsave) string); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.UserUnsave) error); ok {
		r1 = returnFunc(ctx, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthenticator_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockAuthenticator_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - user *model.UserUnsave
func (_e *MockAuthenticator_Expecter) Register(ctx interface{}, user interface{}) *MockAuthenticator_Register_Call {
	return &MockAuthenticator_Register_Call{Call: _e.mock.On("Register", ctx, user)}
}

func (_c *MockAuthenticator_Register_Call) Run(run func(ctx context.Context, user *model.UserUnsave)) *MockAuthenticator_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.UserUnsave
		if args[1] != nil {
			arg1 = args[1].(*model.UserUnsave)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthenticator_Register_Call) Return(s string, err error) *MockAuthenticator_Register_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockAuthenticator_Register_Call) RunAndReturn(run func(ctx context.Context, user *model.UserUnsave) (string, error)) *MockAuthenticator_Register_Call {
	_c.Call.Return(run)
	return _c
}
