// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package middleware

import (
	"context"

	"github.com/eshadow1/gophkeeper/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockJWTWorker creates a new instance of MockJWTWorker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJWTWorker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJWTWorker {
	mock := &MockJWTWorker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockJWTWorker is an autogenerated mock type for the JWTWorker type
type MockJWTWorker struct {
	mock.Mock
}

type MockJWTWorker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJWTWorker) EXPECT() *MockJWTWorker_Expecter {
	return &MockJWTWorker_Expecter{mock: &_m.Mock}
}

// GetUID provides a mock function for the type MockJWTWorker
func (_mock *MockJWTWorker) GetUID(context1 context.Context, s string, bytes []byte) (model.TokenAuth, error) {
	ret := _mock.Called(context1, s, bytes)

	if len(ret) == 0 {
		panic("no return value specified for GetUID")
	}

	var r0 model.TokenAuth
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte) (model.TokenAuth, error)); ok {
		return returnFunc(context1, s, bytes)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte) model.TokenAuth); ok {
		r0 = returnFunc(context1, s, bytes)
	} else {
		r0 = ret.Get(0).(model.TokenAuth)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []byte) error); ok {
		r1 = returnFunc(context1, s, bytes)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJWTWorker_GetUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUID'
type MockJWTWorker_GetUID_Call struct {
	*mock.Call
}

// GetUID is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - bytes []byte
func (_e *MockJWTWorker_Expecter) GetUID(context1 interface{}, s interface{}, bytes interface{}) *MockJWTWorker_GetUID_Call {
	return &MockJWTWorker_GetUID_Call{Call: _e.mock.On("GetUID", context1, s, bytes)}
}

func (_c *MockJWTWorker_GetUID_Call) Run(run func(context1 context.Context, s string, bytes []byte)) *MockJWTWorker_GetUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockJWTWorker_GetUID_Call) Return(tokenAuth model.TokenAuth, err error) *MockJWTWorker_GetUID_Call {
	_c.Call.Return(tokenAuth, err)
	return _c
}

func (_c *MockJWTWorker_GetUID_Call) RunAndReturn(run func(context1 context.Context, s string, bytes []byte) (model.TokenAuth, error)) *MockJWTWorker_GetUID_Call {
	_c.Call.Return(run)
	return _c
}
