// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"context"

	"github.com/eshadow1/gophkeeper/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAuthRepository creates a new instance of MockAuthRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthRepository {
	mock := &MockAuthRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthRepository is an autogenerated mock type for the AuthRepository type
type MockAuthRepository struct {
	mock.Mock
}

type MockAuthRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthRepository) EXPECT() *MockAuthRepository_Expecter {
	return &MockAuthRepository_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockAuthRepository
func (_mock *MockAuthRepository) Close() {
	_mock.Called()
	return
}

// MockAuthRepository_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockAuthRepository_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockAuthRepository_Expecter) Close() *MockAuthRepository_Close_Call {
	return &MockAuthRepository_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockAuthRepository_Close_Call) Run(run func()) *MockAuthRepository_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAuthRepository_Close_Call) Return() *MockAuthRepository_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAuthRepository_Close_Call) RunAndReturn(run func()) *MockAuthRepository_Close_Call {
	_c.Run(run)
	return _c
}

// CreateUser provides a mock function for the type MockAuthRepository
func (_mock *MockAuthRepository) CreateUser(context1 context.Context, user *model.User) (*model.User, error) {
	ret := _mock.Called(context1, user)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 *model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.User) (*model.User, error)); ok {
		return returnFunc(context1, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.User) *model.User); ok {
		r0 = returnFunc(context1, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.User) error); ok {
		r1 = returnFunc(context1, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthRepository_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockAuthRepository_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - context1 context.Context
//   - user *model.User
func (_e *MockAuthRepository_Expecter) CreateUser(context1 interface{}, user interface{}) *MockAuthRepository_CreateUser_Call {
	return &MockAuthRepository_CreateUser_Call{Call: _e.mock.On("CreateUser", context1, user)}
}

func (_c *MockAuthRepository_CreateUser_Call) Run(run func(context1 context.Context, user *model.User)) *MockAuthRepository_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.User
		if args[1] != nil {
			arg1 = args[1].(*model.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthRepository_CreateUser_Call) Return(user1 *model.User, err error) *MockAuthRepository_CreateUser_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *MockAuthRepository_CreateUser_Call) RunAndReturn(run func(context1 context.Context, user *model.User) (*model.User, error)) *MockAuthRepository_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUser provides a mock function for the type MockAuthRepository
func (_mock *MockAuthRepository) GetUser(context1 context.Context, s string) (*model.User, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 *model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.User, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.User); ok {
		r0 = returnFunc(context1, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthRepository_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type MockAuthRepository_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockAuthRepository_Expecter) GetUser(context1 interface{}, s interface{}) *MockAuthRepository_GetUser_Call {
	return &MockAuthRepository_GetUser_Call{Call: _e.mock.On("GetUser", context1, s)}
}

func (_c *MockAuthRepository_GetUser_Call) Run(run func(context1 context.Context, s string)) *MockAuthRepository_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthRepository_GetUser_Call) Return(user *model.User, err error) *MockAuthRepository_GetUser_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockAuthRepository_GetUser_Call) RunAndReturn(run func(context1 context.Context, s string) (*model.User, error)) *MockAuthRepository_GetUser_Call {
	_c.Call.Return(run)
	return _c
}
