// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"github.com/eshadow1/gophkeeper/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Clear provides a mock function for the type MockRepository
func (_mock *MockRepository) Clear() {
	_mock.Called()
	return
}

// MockRepository_Clear_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Clear'
type MockRepository_Clear_Call struct {
	*mock.Call
}

// Clear is a helper method to define mock.On call
func (_e *MockRepository_Expecter) Clear() *MockRepository_Clear_Call {
	return &MockRepository_Clear_Call{Call: _e.mock.On("Clear")}
}

func (_c *MockRepository_Clear_Call) Run(run func()) *MockRepository_Clear_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepository_Clear_Call) Return() *MockRepository_Clear_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRepository_Clear_Call) RunAndReturn(run func()) *MockRepository_Clear_Call {
	_c.Run(run)
	return _c
}

// Count provides a mock function for the type MockRepository
func (_mock *MockRepository) Count() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// MockRepository_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type MockRepository_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
func (_e *MockRepository_Expecter) Count() *MockRepository_Count_Call {
	return &MockRepository_Count_Call{Call: _e.mock.On("Count")}
}

func (_c *MockRepository_Count_Call) Run(run func()) *MockRepository_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepository_Count_Call) Return(n int) *MockRepository_Count_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockRepository_Count_Call) RunAndReturn(run func() int) *MockRepository_Count_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function for the type MockRepository
func (_mock *MockRepository) GetAll() []*model.Item {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []*model.Item
	if returnFunc, ok := ret.Get(0).(func() []*model.Item); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Item)
		}
	}
	return r0
}

// MockRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
func (_e *MockRepository_Expecter) GetAll() *MockRepository_GetAll_Call {
	return &MockRepository_GetAll_Call{Call: _e.mock.On("GetAll")}
}

func (_c *MockRepository_GetAll_Call) Run(run func()) *MockRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepository_GetAll_Call) Return(items []*model.Item) *MockRepository_GetAll_Call {
	_c.Call.Return(items)
	return _c
}

func (_c *MockRepository_GetAll_Call) RunAndReturn(run func() []*model.Item) *MockRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockRepository
func (_mock *MockRepository) Save(item *model.Item) {
	_mock.Called(item)
	return
}

// MockRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - item *model.Item
func (_e *MockRepository_Expecter) Save(item interface{}) *MockRepository_Save_Call {
	return &MockRepository_Save_Call{Call: _e.mock.On("Save", item)}
}

func (_c *MockRepository_Save_Call) Run(run func(item *model.Item)) *MockRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *model.Item
		if args[0] != nil {
			arg0 = args[0].(*model.Item)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_Save_Call) Return() *MockRepository_Save_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRepository_Save_Call) RunAndReturn(run func(item *model.Item)) *MockRepository_Save_Call {
	_c.Run(run)
	return _c
}
