// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockUpdateUsers creates a new instance of MockUpdateUsers. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUpdateUsers(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUpdateUsers {
	mock := &MockUpdateUsers{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUpdateUsers is an autogenerated mock type for the UpdateUsers type
type MockUpdateUsers struct {
	mock.Mock
}

type MockUpdateUsers_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUpdateUsers) EXPECT() *MockUpdateUsers_Expecter {
	return &MockUpdateUsers_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockUpdateUsers
func (_mock *MockUpdateUsers) Get(userID string) (time.Time, error) {
	ret := _mock.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 time.Time
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (time.Time, error)); ok {
		return returnFunc(userID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) time.Time); ok {
		r0 = returnFunc(userID)
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUpdateUsers_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockUpdateUsers_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - userID string
func (_e *MockUpdateUsers_Expecter) Get(userID interface{}) *MockUpdateUsers_Get_Call {
	return &MockUpdateUsers_Get_Call{Call: _e.mock.On("Get", userID)}
}

func (_c *MockUpdateUsers_Get_Call) Run(run func(userID string)) *MockUpdateUsers_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUpdateUsers_Get_Call) Return(time1 time.Time, err error) *MockUpdateUsers_Get_Call {
	_c.Call.Return(time1, err)
	return _c
}

func (_c *MockUpdateUsers_Get_Call) RunAndReturn(run func(userID string) (time.Time, error)) *MockUpdateUsers_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockUpdateUsers
func (_mock *MockUpdateUsers) Update(userID string, timeUpdate time.Time) {
	_mock.Called(userID, timeUpdate)
	return
}

// MockUpdateUsers_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockUpdateUsers_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - userID string
//   - timeUpdate time.Time
func (_e *MockUpdateUsers_Expecter) Update(userID interface{}, timeUpdate interface{}) *MockUpdateUsers_Update_Call {
	return &MockUpdateUsers_Update_Call{Call: _e.mock.On("Update", userID, timeUpdate)}
}

func (_c *MockUpdateUsers_Update_Call) Run(run func(userID string, timeUpdate time.Time)) *MockUpdateUsers_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUpdateUsers_Update_Call) Return() *MockUpdateUsers_Update_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockUpdateUsers_Update_Call) RunAndReturn(run func(userID string, timeUpdate time.Time)) *MockUpdateUsers_Update_Call {
	_c.Run(run)
	return _c
}
