// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockCryptographer creates a new instance of MockCryptographer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCryptographer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCryptographer {
	mock := &MockCryptographer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCryptographer is an autogenerated mock type for the Cryptographer type
type MockCryptographer struct {
	mock.Mock
}

type MockCryptographer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCryptographer) EXPECT() *MockCryptographer_Expecter {
	return &MockCryptographer_Expecter{mock: &_m.Mock}
}

// Decrypt provides a mock function for the type MockCryptographer
func (_mock *MockCryptographer) Decrypt(ciphertext []byte, key []byte) ([]byte, error) {
	ret := _mock.Called(ciphertext, key)

	if len(ret) == 0 {
		panic("no return value specified for Decrypt")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte, []byte) ([]byte, error)); ok {
		return returnFunc(ciphertext, key)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte, []byte) []byte); ok {
		r0 = returnFunc(ciphertext, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]byte, []byte) error); ok {
		r1 = returnFunc(ciphertext, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCryptographer_Decrypt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Decrypt'
type MockCryptographer_Decrypt_Call struct {
	*mock.Call
}

// Decrypt is a helper method to define mock.On call
//   - ciphertext []byte
//   - key []byte
func (_e *MockCryptographer_Expecter) Decrypt(ciphertext interface{}, key interface{}) *MockCryptographer_Decrypt_Call {
	return &MockCryptographer_Decrypt_Call{Call: _e.mock.On("Decrypt", ciphertext, key)}
}

func (_c *MockCryptographer_Decrypt_Call) Run(run func(ciphertext []byte, key []byte)) *MockCryptographer_Decrypt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCryptographer_Decrypt_Call) Return(bytes []byte, err error) *MockCryptographer_Decrypt_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockCryptographer_Decrypt_Call) RunAndReturn(run func(ciphertext []byte, key []byte) ([]byte, error)) *MockCryptographer_Decrypt_Call {
	_c.Call.Return(run)
	return _c
}

// Encrypt provides a mock function for the type MockCryptographer
func (_mock *MockCryptographer) Encrypt(plaintext []byte, key []byte) ([]byte, error) {
	ret := _mock.Called(plaintext, key)

	if len(ret) == 0 {
		panic("no return value specified for Encrypt")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte, []byte) ([]byte, error)); ok {
		return returnFunc(plaintext, key)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte, []byte) []byte); ok {
		r0 = returnFunc(plaintext, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]byte, []byte) error); ok {
		r1 = returnFunc(plaintext, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCryptographer_Encrypt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Encrypt'
type MockCryptographer_Encrypt_Call struct {
	*mock.Call
}

// Encrypt is a helper method to define mock.On call
//   - plaintext []byte
//   - key []byte
func (_e *MockCryptographer_Expecter) Encrypt(plaintext interface{}, key interface{}) *MockCryptographer_Encrypt_Call {
	return &MockCryptographer_Encrypt_Call{Call: _e.mock.On("Encrypt", plaintext, key)}
}

func (_c *MockCryptographer_Encrypt_Call) Run(run func(plaintext []byte, key []byte)) *MockCryptographer_Encrypt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCryptographer_Encrypt_Call) Return(bytes []byte, err error) *MockCryptographer_Encrypt_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockCryptographer_Encrypt_Call) RunAndReturn(run func(plaintext []byte, key []byte) ([]byte, error)) *MockCryptographer_Encrypt_Call {
	_c.Call.Return(run)
	return _c
}
