// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"context"

	"github.com/eshadow1/gophkeeper/gen/pb"
	mock "github.com/stretchr/testify/mock"
)

// NewMockGRPCClient creates a new instance of MockGRPCClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGRPCClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGRPCClient {
	mock := &MockGRPCClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGRPCClient is an autogenerated mock type for the GRPCClient type
type MockGRPCClient struct {
	mock.Mock
}

type MockGRPCClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGRPCClient) EXPECT() *MockGRPCClient_Expecter {
	return &MockGRPCClient_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockGRPCClient
func (_mock *MockGRPCClient) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGRPCClient_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockGRPCClient_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockGRPCClient_Expecter) Close() *MockGRPCClient_Close_Call {
	return &MockGRPCClient_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockGRPCClient_Close_Call) Run(run func()) *MockGRPCClient_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGRPCClient_Close_Call) Return(err error) *MockGRPCClient_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGRPCClient_Close_Call) RunAndReturn(run func() error) *MockGRPCClient_Close_Call {
	_c.Call.Return(run)
	return _c
}

// CreateItem provides a mock function for the type MockGRPCClient
func (_mock *MockGRPCClient) CreateItem(ctx context.Context, dataType string, encryptedData []byte, metaInfo string) (*pb.Item, error) {
	ret := _mock.Called(ctx, dataType, encryptedData, metaInfo)

	if len(ret) == 0 {
		panic("no return value specified for CreateItem")
	}

	var r0 *pb.Item
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte, string) (*pb.Item, error)); ok {
		return returnFunc(ctx, dataType, encryptedData, metaInfo)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte, string) *pb.Item); ok {
		r0 = returnFunc(ctx, dataType, encryptedData, metaInfo)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pb.Item)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []byte, string) error); ok {
		r1 = returnFunc(ctx, dataType, encryptedData, metaInfo)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGRPCClient_CreateItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateItem'
type MockGRPCClient_CreateItem_Call struct {
	*mock.Call
}

// CreateItem is a helper method to define mock.On call
//   - ctx context.Context
//   - dataType string
//   - encryptedData []byte
//   - metaInfo string
func (_e *MockGRPCClient_Expecter) CreateItem(ctx interface{}, dataType interface{}, encryptedData interface{}, metaInfo interface{}) *MockGRPCClient_CreateItem_Call {
	return &MockGRPCClient_CreateItem_Call{Call: _e.mock.On("CreateItem", ctx, dataType, encryptedData, metaInfo)}
}

func (_c *MockGRPCClient_CreateItem_Call) Run(run func(ctx context.Context, dataType string, encryptedData []byte, metaInfo string)) *MockGRPCClient_CreateItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockGRPCClient_CreateItem_Call) Return(item *pb.Item, err error) *MockGRPCClient_CreateItem_Call {
	_c.Call.Return(item, err)
	return _c
}

func (_c *MockGRPCClient_CreateItem_Call) RunAndReturn(run func(ctx context.Context, dataType string, encryptedData []byte, metaInfo string) (*pb.Item, error)) *MockGRPCClient_CreateItem_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteItem provides a mock function for the type MockGRPCClient
func (_mock *MockGRPCClient) DeleteItem(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteItem")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGRPCClient_DeleteItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteItem'
type MockGRPCClient_DeleteItem_Call struct {
	*mock.Call
}

// DeleteItem is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockGRPCClient_Expecter) DeleteItem(ctx interface{}, id interface{}) *MockGRPCClient_DeleteItem_Call {
	return &MockGRPCClient_DeleteItem_Call{Call: _e.mock.On("DeleteItem", ctx, id)}
}

func (_c *MockGRPCClient_DeleteItem_Call) Run(run func(ctx context.Context, id string)) *MockGRPCClient_DeleteItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGRPCClient_DeleteItem_Call) Return(err error) *MockGRPCClient_DeleteItem_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGRPCClient_DeleteItem_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockGRPCClient_DeleteItem_Call {
	_c.Call.Return(run)
	return _c
}

// GetItems provides a mock function for the type MockGRPCClient
func (_mock *MockGRPCClient) GetItems(ctx context.Context, timeUpdate int64) ([]*pb.Item, error) {
	ret := _mock.Called(ctx, timeUpdate)

	if len(ret) == 0 {
		panic("no return value specified for GetItems")
	}

	var r0 []*pb.Item
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) ([]*pb.Item, error)); ok {
		return returnFunc(ctx, timeUpdate)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) []*pb.Item); ok {
		r0 = returnFunc(ctx, timeUpdate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*pb.Item)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, timeUpdate)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGRPCClient_GetItems_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetItems'
type MockGRPCClient_GetItems_Call struct {
	*mock.Call
}

// GetItems is a helper method to define mock.On call
//   - ctx context.Context
//   - timeUpdate int64
func (_e *MockGRPCClient_Expecter) GetItems(ctx interface{}, timeUpdate interface{}) *MockGRPCClient_GetItems_Call {
	return &MockGRPCClient_GetItems_Call{Call: _e.mock.On("GetItems", ctx, timeUpdate)}
}

func (_c *MockGRPCClient_GetItems_Call) Run(run func(ctx context.Context, timeUpdate int64)) *MockGRPCClient_GetItems_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGRPCClient_GetItems_Call) Return(items []*pb.Item, err error) *MockGRPCClient_GetItems_Call {
	_c.Call.Return(items, err)
	return _c
}

func (_c *MockGRPCClient_GetItems_Call) RunAndReturn(run func(ctx context.Context, timeUpdate int64) ([]*pb.Item, error)) *MockGRPCClient_GetItems_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function for the type MockGRPCClient
func (_mock *MockGRPCClient) Login(ctx context.Context, username string, password string) (string, error) {
	ret := _mock.Called(ctx, username, password)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return returnFunc(ctx, username, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = returnFunc(ctx, username, password)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, username, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGRPCClient_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockGRPCClient_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
//   - password string
func (_e *MockGRPCClient_Expecter) Login(ctx interface{}, username interface{}, password interface{}) *MockGRPCClient_Login_Call {
	return &MockGRPCClient_Login_Call{Call: _e.mock.On("Login", ctx, username, password)}
}

func (_c *MockGRPCClient_Login_Call) Run(run func(ctx context.Context, username string, password string)) *MockGRPCClient_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGRPCClient_Login_Call) Return(s string, err error) *MockGRPCClient_Login_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockGRPCClient_Login_Call) RunAndReturn(run func(ctx context.Context, username string, password string) (string, error)) *MockGRPCClient_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function for the type MockGRPCClient
func (_mock *MockGRPCClient) Register(ctx context.Context, username string, password string) (string, error) {
	ret := _mock.Called(ctx, username, password)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return returnFunc(ctx, username, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = returnFunc(ctx, username, password)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, username, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGRPCClient_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockGRPCClient_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
//   - password string
func (_e *MockGRPCClient_Expecter) Register(ctx interface{}, username interface{}, password interface{}) *MockGRPCClient_Register_Call {
	return &MockGRPCClient_Register_Call{Call: _e.mock.On("Register", ctx, username, password)}
}

func (_c *MockGRPCClient_Register_Call) Run(run func(ctx context.Context, username string, password string)) *MockGRPCClient_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGRPCClient_Register_Call) Return(s string, err error) *MockGRPCClient_Register_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockGRPCClient_Register_Call) RunAndReturn(run func(ctx context.Context, username string, password string) (string, error)) *MockGRPCClient_Register_Call {
	_c.Call.Return(run)
	return _c
}

// SetToken provides a mock function for the type MockGRPCClient
func (_mock *MockGRPCClient) SetToken(token string) {
	_mock.Called(token)
	return
}

// MockGRPCClient_SetToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetToken'
type MockGRPCClient_SetToken_Call struct {
	*mock.Call
}

// SetToken is a helper method to define mock.On call
//   - token string
func (_e *MockGRPCClient_Expecter) SetToken(token interface{}) *MockGRPCClient_SetToken_Call {
	return &MockGRPCClient_SetToken_Call{Call: _e.mock.On("SetToken", token)}
}

func (_c *MockGRPCClient_SetToken_Call) Run(run func(token string)) *MockGRPCClient_SetToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockGRPCClient_SetToken_Call) Return() *MockGRPCClient_SetToken_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockGRPCClient_SetToken_Call) RunAndReturn(run func(token string)) *MockGRPCClient_SetToken_Call {
	_c.Run(run)
	return _c
}

// UpdateItem provides a mock function for the type MockGRPCClient
func (_mock *MockGRPCClient) UpdateItem(ctx context.Context, id string, dataType string, encryptedData []byte, metaInfo string) error {
	ret := _mock.Called(ctx, id, dataType, encryptedData, metaInfo)

	if len(ret) == 0 {
		panic("no return value specified for UpdateItem")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, []byte, string) error); ok {
		r0 = returnFunc(ctx, id, dataType, encryptedData, metaInfo)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGRPCClient_UpdateItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateItem'
type MockGRPCClient_UpdateItem_Call struct {
	*mock.Call
}

// UpdateItem is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - dataType string
//   - encryptedData []byte
//   - metaInfo string
func (_e *MockGRPCClient_Expecter) UpdateItem(ctx interface{}, id interface{}, dataType interface{}, encryptedData interface{}, metaInfo interface{}) *MockGRPCClient_UpdateItem_Call {
	return &MockGRPCClient_UpdateItem_Call{Call: _e.mock.On("UpdateItem", ctx, id, dataType, encryptedData, metaInfo)}
}

func (_c *MockGRPCClient_UpdateItem_Call) Run(run func(ctx context.Context, id string, dataType string, encryptedData []byte, metaInfo string)) *MockGRPCClient_UpdateItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []byte
		if args[3] != nil {
			arg3 = args[3].([]byte)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockGRPCClient_UpdateItem_Call) Return(err error) *MockGRPCClient_UpdateItem_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGRPCClient_UpdateItem_Call) RunAndReturn(run func(ctx context.Context, id string, dataType string, encryptedData []byte, metaInfo string) error) *MockGRPCClient_UpdateItem_Call {
	_c.Call.Return(run)
	return _c
}
