// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockAuthWorker creates a new instance of MockAuthWorker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthWorker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthWorker {
	mock := &MockAuthWorker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthWorker is an autogenerated mock type for the AuthWorker type
type MockAuthWorker struct {
	mock.Mock
}

type MockAuthWorker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthWorker) EXPECT() *MockAuthWorker_Expecter {
	return &MockAuthWorker_Expecter{mock: &_m.Mock}
}

// CreateJWT provides a mock function for the type MockAuthWorker
func (_mock *MockAuthWorker) CreateJWT(userID string, secret []byte) (string, error) {
	ret := _mock.Called(userID, secret)

	if len(ret) == 0 {
		panic("no return value specified for CreateJWT")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, []byte) (string, error)); ok {
		return returnFunc(userID, secret)
	}
	if returnFunc, ok := ret.Get(0).(func(string, []byte) string); ok {
		r0 = returnFunc(userID, secret)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string, []byte) error); ok {
		r1 = returnFunc(userID, secret)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthWorker_CreateJWT_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateJWT'
type MockAuthWorker_CreateJWT_Call struct {
	*mock.Call
}

// CreateJWT is a helper method to define mock.On call
//   - userID string
//   - secret []byte
func (_e *MockAuthWorker_Expecter) CreateJWT(userID interface{}, secret interface{}) *MockAuthWorker_CreateJWT_Call {
	return &MockAuthWorker_CreateJWT_Call{Call: _e.mock.On("CreateJWT", userID, secret)}
}

func (_c *MockAuthWorker_CreateJWT_Call) Run(run func(userID string, secret []byte)) *MockAuthWorker_CreateJWT_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthWorker_CreateJWT_Call) Return(s string, err error) *MockAuthWorker_CreateJWT_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockAuthWorker_CreateJWT_Call) RunAndReturn(run func(userID string, secret []byte) (string, error)) *MockAuthWorker_CreateJWT_Call {
	_c.Call.Return(run)
	return _c
}
