// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"context"

	"github.com/eshadow1/gophkeeper/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockKeeperRepository creates a new instance of MockKeeperRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockKeeperRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockKeeperRepository {
	mock := &MockKeeperRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockKeeperRepository is an autogenerated mock type for the KeeperRepository type
type MockKeeperRepository struct {
	mock.Mock
}

type MockKeeperRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockKeeperRepository) EXPECT() *MockKeeperRepository_Expecter {
	return &MockKeeperRepository_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockKeeperRepository
func (_mock *MockKeeperRepository) Close() {
	_mock.Called()
	return
}

// MockKeeperRepository_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockKeeperRepository_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockKeeperRepository_Expecter) Close() *MockKeeperRepository_Close_Call {
	return &MockKeeperRepository_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockKeeperRepository_Close_Call) Run(run func()) *MockKeeperRepository_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockKeeperRepository_Close_Call) Return() *MockKeeperRepository_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockKeeperRepository_Close_Call) RunAndReturn(run func()) *MockKeeperRepository_Close_Call {
	_c.Run(run)
	return _c
}

// CreateItem provides a mock function for the type MockKeeperRepository
func (_mock *MockKeeperRepository) CreateItem(ctx context.Context, item *model.ItemDB) (*model.ItemDB, error) {
	ret := _mock.Called(ctx, item)

	if len(ret) == 0 {
		panic("no return value specified for CreateItem")
	}

	var r0 *model.ItemDB
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.ItemDB) (*model.ItemDB, error)); ok {
		return returnFunc(ctx, item)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.ItemDB) *model.ItemDB); ok {
		r0 = returnFunc(ctx, item)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ItemDB)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.ItemDB) error); ok {
		r1 = returnFunc(ctx, item)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKeeperRepository_CreateItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateItem'
type MockKeeperRepository_CreateItem_Call struct {
	*mock.Call
}

// CreateItem is a helper method to define mock.On call
//   - ctx context.Context
//   - item *model.ItemDB
func (_e *MockKeeperRepository_Expecter) CreateItem(ctx interface{}, item interface{}) *MockKeeperRepository_CreateItem_Call {
	return &MockKeeperRepository_CreateItem_Call{Call: _e.mock.On("CreateItem", ctx, item)}
}

func (_c *MockKeeperRepository_CreateItem_Call) Run(run func(ctx context.Context, item *model.ItemDB)) *MockKeeperRepository_CreateItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.ItemDB
		if args[1] != nil {
			arg1 = args[1].(*model.ItemDB)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockKeeperRepository_CreateItem_Call) Return(itemDB *model.ItemDB, err error) *MockKeeperRepository_CreateItem_Call {
	_c.Call.Return(itemDB, err)
	return _c
}

func (_c *MockKeeperRepository_CreateItem_Call) RunAndReturn(run func(ctx context.Context, item *model.ItemDB) (*model.ItemDB, error)) *MockKeeperRepository_CreateItem_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteItem provides a mock function for the type MockKeeperRepository
func (_mock *MockKeeperRepository) DeleteItem(ctx context.Context, item *model.ItemDB) error {
	ret := _mock.Called(ctx, item)

	if len(ret) == 0 {
		panic("no return value specified for DeleteItem")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.ItemDB) error); ok {
		r0 = returnFunc(ctx, item)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockKeeperRepository_DeleteItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteItem'
type MockKeeperRepository_DeleteItem_Call struct {
	*mock.Call
}

// DeleteItem is a helper method to define mock.On call
//   - ctx context.Context
//   - item *model.ItemDB
func (_e *MockKeeperRepository_Expecter) DeleteItem(ctx interface{}, item interface{}) *MockKeeperRepository_DeleteItem_Call {
	return &MockKeeperRepository_DeleteItem_Call{Call: _e.mock.On("DeleteItem", ctx, item)}
}

func (_c *MockKeeperRepository_DeleteItem_Call) Run(run func(ctx context.Context, item *model.ItemDB)) *MockKeeperRepository_DeleteItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.ItemDB
		if args[1] != nil {
			arg1 = args[1].(*model.ItemDB)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockKeeperRepository_DeleteItem_Call) Return(err error) *MockKeeperRepository_DeleteItem_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockKeeperRepository_DeleteItem_Call) RunAndReturn(run func(ctx context.Context, item *model.ItemDB) error) *MockKeeperRepository_DeleteItem_Call {
	_c.Call.Return(run)
	return _c
}

// GetItemsByUserID provides a mock function for the type MockKeeperRepository
func (_mock *MockKeeperRepository) GetItemsByUserID(ctx context.Context, userID string) ([]*model.ItemDB, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetItemsByUserID")
	}

	var r0 []*model.ItemDB
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*model.ItemDB, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*model.ItemDB); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.ItemDB)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKeeperRepository_GetItemsByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetItemsByUserID'
type MockKeeperRepository_GetItemsByUserID_Call struct {
	*mock.Call
}

// GetItemsByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockKeeperRepository_Expecter) GetItemsByUserID(ctx interface{}, userID interface{}) *MockKeeperRepository_GetItemsByUserID_Call {
	return &MockKeeperRepository_GetItemsByUserID_Call{Call: _e.mock.On("GetItemsByUserID", ctx, userID)}
}

func (_c *MockKeeperRepository_GetItemsByUserID_Call) Run(run func(ctx context.Context, userID string)) *MockKeeperRepository_GetItemsByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockKeeperRepository_GetItemsByUserID_Call) Return(itemDBs []*model.ItemDB, err error) *MockKeeperRepository_GetItemsByUserID_Call {
	_c.Call.Return(itemDBs, err)
	return _c
}

func (_c *MockKeeperRepository_GetItemsByUserID_Call) RunAndReturn(run func(ctx context.Context, userID string) ([]*model.ItemDB, error)) *MockKeeperRepository_GetItemsByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateItem provides a mock function for the type MockKeeperRepository
func (_mock *MockKeeperRepository) UpdateItem(ctx context.Context, item *model.ItemDB) error {
	ret := _mock.Called(ctx, item)

	if len(ret) == 0 {
		panic("no return value specified for UpdateItem")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.ItemDB) error); ok {
		r0 = returnFunc(ctx, item)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockKeeperRepository_UpdateItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateItem'
type MockKeeperRepository_UpdateItem_Call struct {
	*mock.Call
}

// UpdateItem is a helper method to define mock.On call
//   - ctx context.Context
//   - item *model.ItemDB
func (_e *MockKeeperRepository_Expecter) UpdateItem(ctx interface{}, item interface{}) *MockKeeperRepository_UpdateItem_Call {
	return &MockKeeperRepository_UpdateItem_Call{Call: _e.mock.On("UpdateItem", ctx, item)}
}

func (_c *MockKeeperRepository_UpdateItem_Call) Run(run func(ctx context.Context, item *model.ItemDB)) *MockKeeperRepository_UpdateItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.ItemDB
		if args[1] != nil {
			arg1 = args[1].(*model.ItemDB)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockKeeperRepository_UpdateItem_Call) Return(err error) *MockKeeperRepository_UpdateItem_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockKeeperRepository_UpdateItem_Call) RunAndReturn(run func(ctx context.Context, item *model.ItemDB) error) *MockKeeperRepository_UpdateItem_Call {
	_c.Call.Return(run)
	return _c
}
