// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"context"

	"github.com/eshadow1/gophkeeper/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockValidator creates a new instance of MockValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockValidator {
	mock := &MockValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockValidator is an autogenerated mock type for the Validator type
type MockValidator struct {
	mock.Mock
}

type MockValidator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockValidator) EXPECT() *MockValidator_Expecter {
	return &MockValidator_Expecter{mock: &_m.Mock}
}

// Validate provides a mock function for the type MockValidator
func (_mock *MockValidator) Validate(ctx context.Context, dataType model.ItemType, payload any) error {
	ret := _mock.Called(ctx, dataType, payload)

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.ItemType, any) error); ok {
		r0 = returnFunc(ctx, dataType, payload)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockValidator_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type MockValidator_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
//   - ctx context.Context
//   - dataType model.ItemType
//   - payload any
func (_e *MockValidator_Expecter) Validate(ctx interface{}, dataType interface{}, payload interface{}) *MockValidator_Validate_Call {
	return &MockValidator_Validate_Call{Call: _e.mock.On("Validate", ctx, dataType, payload)}
}

func (_c *MockValidator_Validate_Call) Run(run func(ctx context.Context, dataType model.ItemType, payload any)) *MockValidator_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.ItemType
		if args[1] != nil {
			arg1 = args[1].(model.ItemType)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockValidator_Validate_Call) Return(err error) *MockValidator_Validate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockValidator_Validate_Call) RunAndReturn(run func(ctx context.Context, dataType model.ItemType, payload any) error) *MockValidator_Validate_Call {
	_c.Call.Return(run)
	return _c
}
