// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package tui

import (
	"context"

	"github.com/eshadow1/gophkeeper/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockKeeperClient creates a new instance of MockKeeperClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockKeeperClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockKeeperClient {
	mock := &MockKeeperClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockKeeperClient is an autogenerated mock type for the KeeperClient type
type MockKeeperClient struct {
	mock.Mock
}

type MockKeeperClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockKeeperClient) EXPECT() *MockKeeperClient_Expecter {
	return &MockKeeperClient_Expecter{mock: &_m.Mock}
}

// AddItem provides a mock function for the type MockKeeperClient
func (_mock *MockKeeperClient) AddItem(ctx context.Context, dataType model.ItemType, payload any, metaInfo string) error {
	ret := _mock.Called(ctx, dataType, payload, metaInfo)

	if len(ret) == 0 {
		panic("no return value specified for AddItem")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.ItemType, any, string) error); ok {
		r0 = returnFunc(ctx, dataType, payload, metaInfo)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockKeeperClient_AddItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddItem'
type MockKeeperClient_AddItem_Call struct {
	*mock.Call
}

// AddItem is a helper method to define mock.On call
//   - ctx context.Context
//   - dataType model.ItemType
//   - payload any
//   - metaInfo string
func (_e *MockKeeperClient_Expecter) AddItem(ctx interface{}, dataType interface{}, payload interface{}, metaInfo interface{}) *MockKeeperClient_AddItem_Call {
	return &MockKeeperClient_AddItem_Call{Call: _e.mock.On("AddItem", ctx, dataType, payload, metaInfo)}
}

func (_c *MockKeeperClient_AddItem_Call) Run(run func(ctx context.Context, dataType model.ItemType, payload any, metaInfo string)) *MockKeeperClient_AddItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.ItemType
		if args[1] != nil {
			arg1 = args[1].(model.ItemType)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockKeeperClient_AddItem_Call) Return(err error) *MockKeeperClient_AddItem_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockKeeperClient_AddItem_Call) RunAndReturn(run func(ctx context.Context, dataType model.ItemType, payload any, metaInfo string) error) *MockKeeperClient_AddItem_Call {
	_c.Call.Return(run)
	return _c
}

// DecryptAndParse provides a mock function for the type MockKeeperClient
func (_mock *MockKeeperClient) DecryptAndParse(item *model.Item, payload any) error {
	ret := _mock.Called(item, payload)

	if len(ret) == 0 {
		panic("no return value specified for DecryptAndParse")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*model.Item, any) error); ok {
		r0 = returnFunc(item, payload)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockKeeperClient_DecryptAndParse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DecryptAndParse'
type MockKeeperClient_DecryptAndParse_Call struct {
	*mock.Call
}

// DecryptAndParse is a helper method to define mock.On call
//   - item *model.Item
//   - payload any
func (_e *MockKeeperClient_Expecter) DecryptAndParse(item interface{}, payload interface{}) *MockKeeperClient_DecryptAndParse_Call {
	return &MockKeeperClient_DecryptAndParse_Call{Call: _e.mock.On("DecryptAndParse", item, payload)}
}

func (_c *MockKeeperClient_DecryptAndParse_Call) Run(run func(item *model.Item, payload any)) *MockKeeperClient_DecryptAndParse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *model.Item
		if args[0] != nil {
			arg0 = args[0].(*model.Item)
		}
		var arg1 any
		if args[1] != nil {
			arg1 = args[1].(any)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockKeeperClient_DecryptAndParse_Call) Return(err error) *MockKeeperClient_DecryptAndParse_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockKeeperClient_DecryptAndParse_Call) RunAndReturn(run func(item *model.Item, payload any) error) *MockKeeperClient_DecryptAndParse_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteItem provides a mock function for the type MockKeeperClient
func (_mock *MockKeeperClient) DeleteItem(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteItem")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockKeeperClient_DeleteItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteItem'
type MockKeeperClient_DeleteItem_Call struct {
	*mock.Call
}

// DeleteItem is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockKeeperClient_Expecter) DeleteItem(ctx interface{}, id interface{}) *MockKeeperClient_DeleteItem_Call {
	return &MockKeeperClient_DeleteItem_Call{Call: _e.mock.On("DeleteItem", ctx, id)}
}

func (_c *MockKeeperClient_DeleteItem_Call) Run(run func(ctx context.Context, id string)) *MockKeeperClient_DeleteItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockKeeperClient_DeleteItem_Call) Return(err error) *MockKeeperClient_DeleteItem_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockKeeperClient_DeleteItem_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockKeeperClient_DeleteItem_Call {
	_c.Call.Return(run)
	return _c
}

// ListItems provides a mock function for the type MockKeeperClient
func (_mock *MockKeeperClient) ListItems() []*model.Item {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListItems")
	}

	var r0 []*model.Item
	if returnFunc, ok := ret.Get(0).(func() []*model.Item); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Item)
		}
	}
	return r0
}

// MockKeeperClient_ListItems_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListItems'
type MockKeeperClient_ListItems_Call struct {
	*mock.Call
}

// ListItems is a helper method to define mock.On call
func (_e *MockKeeperClient_Expecter) ListItems() *MockKeeperClient_ListItems_Call {
	return &MockKeeperClient_ListItems_Call{Call: _e.mock.On("ListItems")}
}

func (_c *MockKeeperClient_ListItems_Call) Run(run func()) *MockKeeperClient_ListItems_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockKeeperClient_ListItems_Call) Return(items []*model.Item) *MockKeeperClient_ListItems_Call {
	_c.Call.Return(items)
	return _c
}

func (_c *MockKeeperClient_ListItems_Call) RunAndReturn(run func() []*model.Item) *MockKeeperClient_ListItems_Call {
	_c.Call.Return(run)
	return _c
}

// LoadToken provides a mock function for the type MockKeeperClient
func (_mock *MockKeeperClient) LoadToken() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for LoadToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockKeeperClient_LoadToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadToken'
type MockKeeperClient_LoadToken_Call struct {
	*mock.Call
}

// LoadToken is a helper method to define mock.On call
func (_e *MockKeeperClient_Expecter) LoadToken() *MockKeeperClient_LoadToken_Call {
	return &MockKeeperClient_LoadToken_Call{Call: _e.mock.On("LoadToken")}
}

func (_c *MockKeeperClient_LoadToken_Call) Run(run func()) *MockKeeperClient_LoadToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockKeeperClient_LoadToken_Call) Return(err error) *MockKeeperClient_LoadToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockKeeperClient_LoadToken_Call) RunAndReturn(run func() error) *MockKeeperClient_LoadToken_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function for the type MockKeeperClient
func (_mock *MockKeeperClient) Login(ctx context.Context, username string, password string) error {
	ret := _mock.Called(ctx, username, password)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, username, password)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockKeeperClient_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockKeeperClient_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
//   - password string
func (_e *MockKeeperClient_Expecter) Login(ctx interface{}, username interface{}, password interface{}) *MockKeeperClient_Login_Call {
	return &MockKeeperClient_Login_Call{Call: _e.mock.On("Login", ctx, username, password)}
}

func (_c *MockKeeperClient_Login_Call) Run(run func(ctx context.Context, username string, password string)) *MockKeeperClient_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockKeeperClient_Login_Call) Return(err error) *MockKeeperClient_Login_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockKeeperClient_Login_Call) RunAndReturn(run func(ctx context.Context, username string, password string) error) *MockKeeperClient_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Logout provides a mock function for the type MockKeeperClient
func (_mock *MockKeeperClient) Logout() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockKeeperClient_Logout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logout'
type MockKeeperClient_Logout_Call struct {
	*mock.Call
}

// Logout is a helper method to define mock.On call
func (_e *MockKeeperClient_Expecter) Logout() *MockKeeperClient_Logout_Call {
	return &MockKeeperClient_Logout_Call{Call: _e.mock.On("Logout")}
}

func (_c *MockKeeperClient_Logout_Call) Run(run func()) *MockKeeperClient_Logout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockKeeperClient_Logout_Call) Return(err error) *MockKeeperClient_Logout_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockKeeperClient_Logout_Call) RunAndReturn(run func() error) *MockKeeperClient_Logout_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function for the type MockKeeperClient
func (_mock *MockKeeperClient) Register(ctx context.Context, username string, password string) error {
	ret := _mock.Called(ctx, username, password)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, username, password)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockKeeperClient_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockKeeperClient_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
//   - password string
func (_e *MockKeeperClient_Expecter) Register(ctx interface{}, username interface{}, password interface{}) *MockKeeperClient_Register_Call {
	return &MockKeeperClient_Register_Call{Call: _e.mock.On("Register", ctx, username, password)}
}

func (_c *MockKeeperClient_Register_Call) Run(run func(ctx context.Context, username string, password string)) *MockKeeperClient_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockKeeperClient_Register_Call) Return(err error) *MockKeeperClient_Register_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockKeeperClient_Register_Call) RunAndReturn(run func(ctx context.Context, username string, password string) error) *MockKeeperClient_Register_Call {
	_c.Call.Return(run)
	return _c
}

// SyncFromServer provides a mock function for the type MockKeeperClient
func (_mock *MockKeeperClient) SyncFromServer(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for SyncFromServer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockKeeperClient_SyncFromServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SyncFromServer'
type MockKeeperClient_SyncFromServer_Call struct {
	*mock.Call
}

// SyncFromServer is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockKeeperClient_Expecter) SyncFromServer(ctx interface{}) *MockKeeperClient_SyncFromServer_Call {
	return &MockKeeperClient_SyncFromServer_Call{Call: _e.mock.On("SyncFromServer", ctx)}
}

func (_c *MockKeeperClient_SyncFromServer_Call) Run(run func(ctx context.Context)) *MockKeeperClient_SyncFromServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockKeeperClient_SyncFromServer_Call) Return(err error) *MockKeeperClient_SyncFromServer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockKeeperClient_SyncFromServer_Call) RunAndReturn(run func(ctx context.Context) error) *MockKeeperClient_SyncFromServer_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateItem provides a mock function for the type MockKeeperClient
func (_mock *MockKeeperClient) UpdateItem(ctx context.Context, id string, dataType model.ItemType, payload any, metaInfo string) error {
	ret := _mock.Called(ctx, id, dataType, payload, metaInfo)

	if len(ret) == 0 {
		panic("no return value specified for UpdateItem")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, model.ItemType, any, string) error); ok {
		r0 = returnFunc(ctx, id, dataType, payload, metaInfo)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockKeeperClient_UpdateItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateItem'
type MockKeeperClient_UpdateItem_Call struct {
	*mock.Call
}

// UpdateItem is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - dataType model.ItemType
//   - payload any
//   - metaInfo string
func (_e *MockKeeperClient_Expecter) UpdateItem(ctx interface{}, id interface{}, dataType interface{}, payload interface{}, metaInfo interface{}) *MockKeeperClient_UpdateItem_Call {
	return &MockKeeperClient_UpdateItem_Call{Call: _e.mock.On("UpdateItem", ctx, id, dataType, payload, metaInfo)}
}

func (_c *MockKeeperClient_UpdateItem_Call) Run(run func(ctx context.Context, id string, dataType model.ItemType, payload any, metaInfo string)) *MockKeeperClient_UpdateItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 model.ItemType
		if args[2] != nil {
			arg2 = args[2].(model.ItemType)
		}
		var arg3 any
		if args[3] != nil {
			arg3 = args[3].(any)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockKeeperClient_UpdateItem_Call) Return(err error) *MockKeeperClient_UpdateItem_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockKeeperClient_UpdateItem_Call) RunAndReturn(run func(ctx context.Context, id string, dataType model.ItemType, payload any, metaInfo string) error) *MockKeeperClient_UpdateItem_Call {
	_c.Call.Return(run)
	return _c
}
