// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package tui

import (
	"github.com/charmbracelet/bubbletea"
	"github.com/eshadow1/gophkeeper/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDoingModel creates a new instance of MockDoingModel. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDoingModel(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDoingModel {
	mock := &MockDoingModel{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDoingModel is an autogenerated mock type for the DoingModel type
type MockDoingModel struct {
	mock.Mock
}

type MockDoingModel_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDoingModel) EXPECT() *MockDoingModel_Expecter {
	return &MockDoingModel_Expecter{mock: &_m.Mock}
}

// AddItem provides a mock function for the type MockDoingModel
func (_mock *MockDoingModel) AddItem(dt model.ItemType, payload any, meta string) tea.Cmd {
	ret := _mock.Called(dt, payload, meta)

	if len(ret) == 0 {
		panic("no return value specified for AddItem")
	}

	var r0 tea.Cmd
	if returnFunc, ok := ret.Get(0).(func(model.ItemType, any, string) tea.Cmd); ok {
		r0 = returnFunc(dt, payload, meta)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(tea.Cmd)
		}
	}
	return r0
}

// MockDoingModel_AddItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddItem'
type MockDoingModel_AddItem_Call struct {
	*mock.Call
}

// AddItem is a helper method to define mock.On call
//   - dt model.ItemType
//   - payload any
//   - meta string
func (_e *MockDoingModel_Expecter) AddItem(dt interface{}, payload interface{}, meta interface{}) *MockDoingModel_AddItem_Call {
	return &MockDoingModel_AddItem_Call{Call: _e.mock.On("AddItem", dt, payload, meta)}
}

func (_c *MockDoingModel_AddItem_Call) Run(run func(dt model.ItemType, payload any, meta string)) *MockDoingModel_AddItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 model.ItemType
		if args[0] != nil {
			arg0 = args[0].(model.ItemType)
		}
		var arg1 any
		if args[1] != nil {
			arg1 = args[1].(any)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDoingModel_AddItem_Call) Return(cmd tea.Cmd) *MockDoingModel_AddItem_Call {
	_c.Call.Return(cmd)
	return _c
}

func (_c *MockDoingModel_AddItem_Call) RunAndReturn(run func(dt model.ItemType, payload any, meta string) tea.Cmd) *MockDoingModel_AddItem_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteItem provides a mock function for the type MockDoingModel
func (_mock *MockDoingModel) DeleteItem(id string) tea.Cmd {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteItem")
	}

	var r0 tea.Cmd
	if returnFunc, ok := ret.Get(0).(func(string) tea.Cmd); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(tea.Cmd)
		}
	}
	return r0
}

// MockDoingModel_DeleteItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteItem'
type MockDoingModel_DeleteItem_Call struct {
	*mock.Call
}

// DeleteItem is a helper method to define mock.On call
//   - id string
func (_e *MockDoingModel_Expecter) DeleteItem(id interface{}) *MockDoingModel_DeleteItem_Call {
	return &MockDoingModel_DeleteItem_Call{Call: _e.mock.On("DeleteItem", id)}
}

func (_c *MockDoingModel_DeleteItem_Call) Run(run func(id string)) *MockDoingModel_DeleteItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDoingModel_DeleteItem_Call) Return(cmd tea.Cmd) *MockDoingModel_DeleteItem_Call {
	_c.Call.Return(cmd)
	return _c
}

func (_c *MockDoingModel_DeleteItem_Call) RunAndReturn(run func(id string) tea.Cmd) *MockDoingModel_DeleteItem_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function for the type MockDoingModel
func (_mock *MockDoingModel) Login(u string, p string) tea.Cmd {
	ret := _mock.Called(u, p)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 tea.Cmd
	if returnFunc, ok := ret.Get(0).(func(string, string) tea.Cmd); ok {
		r0 = returnFunc(u, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(tea.Cmd)
		}
	}
	return r0
}

// MockDoingModel_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockDoingModel_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - u string
//   - p string
func (_e *MockDoingModel_Expecter) Login(u interface{}, p interface{}) *MockDoingModel_Login_Call {
	return &MockDoingModel_Login_Call{Call: _e.mock.On("Login", u, p)}
}

func (_c *MockDoingModel_Login_Call) Run(run func(u string, p string)) *MockDoingModel_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDoingModel_Login_Call) Return(cmd tea.Cmd) *MockDoingModel_Login_Call {
	_c.Call.Return(cmd)
	return _c
}

func (_c *MockDoingModel_Login_Call) RunAndReturn(run func(u string, p string) tea.Cmd) *MockDoingModel_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Logout provides a mock function for the type MockDoingModel
func (_mock *MockDoingModel) Logout() tea.Cmd {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 tea.Cmd
	if returnFunc, ok := ret.Get(0).(func() tea.Cmd); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(tea.Cmd)
		}
	}
	return r0
}

// MockDoingModel_Logout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logout'
type MockDoingModel_Logout_Call struct {
	*mock.Call
}

// Logout is a helper method to define mock.On call
func (_e *MockDoingModel_Expecter) Logout() *MockDoingModel_Logout_Call {
	return &MockDoingModel_Logout_Call{Call: _e.mock.On("Logout")}
}

func (_c *MockDoingModel_Logout_Call) Run(run func()) *MockDoingModel_Logout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDoingModel_Logout_Call) Return(cmd tea.Cmd) *MockDoingModel_Logout_Call {
	_c.Call.Return(cmd)
	return _c
}

func (_c *MockDoingModel_Logout_Call) RunAndReturn(run func() tea.Cmd) *MockDoingModel_Logout_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function for the type MockDoingModel
func (_mock *MockDoingModel) Register(u string, p string) tea.Cmd {
	ret := _mock.Called(u, p)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 tea.Cmd
	if returnFunc, ok := ret.Get(0).(func(string, string) tea.Cmd); ok {
		r0 = returnFunc(u, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(tea.Cmd)
		}
	}
	return r0
}

// MockDoingModel_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockDoingModel_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - u string
//   - p string
func (_e *MockDoingModel_Expecter) Register(u interface{}, p interface{}) *MockDoingModel_Register_Call {
	return &MockDoingModel_Register_Call{Call: _e.mock.On("Register", u, p)}
}

func (_c *MockDoingModel_Register_Call) Run(run func(u string, p string)) *MockDoingModel_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDoingModel_Register_Call) Return(cmd tea.Cmd) *MockDoingModel_Register_Call {
	_c.Call.Return(cmd)
	return _c
}

func (_c *MockDoingModel_Register_Call) RunAndReturn(run func(u string, p string) tea.Cmd) *MockDoingModel_Register_Call {
	_c.Call.Return(run)
	return _c
}

// Sync provides a mock function for the type MockDoingModel
func (_mock *MockDoingModel) Sync() tea.Cmd {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Sync")
	}

	var r0 tea.Cmd
	if returnFunc, ok := ret.Get(0).(func() tea.Cmd); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(tea.Cmd)
		}
	}
	return r0
}

// MockDoingModel_Sync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sync'
type MockDoingModel_Sync_Call struct {
	*mock.Call
}

// Sync is a helper method to define mock.On call
func (_e *MockDoingModel_Expecter) Sync() *MockDoingModel_Sync_Call {
	return &MockDoingModel_Sync_Call{Call: _e.mock.On("Sync")}
}

func (_c *MockDoingModel_Sync_Call) Run(run func()) *MockDoingModel_Sync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDoingModel_Sync_Call) Return(cmd tea.Cmd) *MockDoingModel_Sync_Call {
	_c.Call.Return(cmd)
	return _c
}

func (_c *MockDoingModel_Sync_Call) RunAndReturn(run func() tea.Cmd) *MockDoingModel_Sync_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateItem provides a mock function for the type MockDoingModel
func (_mock *MockDoingModel) UpdateItem(id string, dt model.ItemType, payload any, meta string) tea.Cmd {
	ret := _mock.Called(id, dt, payload, meta)

	if len(ret) == 0 {
		panic("no return value specified for UpdateItem")
	}

	var r0 tea.Cmd
	if returnFunc, ok := ret.Get(0).(func(string, model.ItemType, any, string) tea.Cmd); ok {
		r0 = returnFunc(id, dt, payload, meta)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(tea.Cmd)
		}
	}
	return r0
}

// MockDoingModel_UpdateItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateItem'
type MockDoingModel_UpdateItem_Call struct {
	*mock.Call
}

// UpdateItem is a helper method to define mock.On call
//   - id string
//   - dt model.ItemType
//   - payload any
//   - meta string
func (_e *MockDoingModel_Expecter) UpdateItem(id interface{}, dt interface{}, payload interface{}, meta interface{}) *MockDoingModel_UpdateItem_Call {
	return &MockDoingModel_UpdateItem_Call{Call: _e.mock.On("UpdateItem", id, dt, payload, meta)}
}

func (_c *MockDoingModel_UpdateItem_Call) Run(run func(id string, dt model.ItemType, payload any, meta string)) *MockDoingModel_UpdateItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 model.ItemType
		if args[1] != nil {
			arg1 = args[1].(model.ItemType)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockDoingModel_UpdateItem_Call) Return(cmd tea.Cmd) *MockDoingModel_UpdateItem_Call {
	_c.Call.Return(cmd)
	return _c
}

func (_c *MockDoingModel_UpdateItem_Call) RunAndReturn(run func(id string, dt model.ItemType, payload any, meta string) tea.Cmd) *MockDoingModel_UpdateItem_Call {
	_c.Call.Return(run)
	return _c
}
